---
data:
  sway:
    font_size: 13
    tray_output: 'eDP-1'
    nm_applet: true
    additional_bindings: ''
    inputs: |-
      input <identifier> {
      }
    outputs: |-
      output <identifier> {
      }
  hyprland:
    monitors:
      identifier: "resolution@refresh_rate, auto, 1, vrr, 0"
    input:
      keyboard_layouts: |-
        kb_layout = us,rs,rs,de
        kb_variant = ,latinunicode,,
      sensitivity: "1"
  bumblebee:
    modules: 'ytrssil,'
    parameters:
      - key: "sensors.path"
        value: "coretemp-isa-0000/Package id 0/temp1_input"
  alacritty:
    font:
      size: '7.5'
      offset:
        x: 0
        y: 3
  ghostty:
    font:
      size: '14'
      cell_width: -1
      cell_height: 1
  rofi:
    font:
      size: '15'
  zshrc:
    env_vars:
      - name: 'NAME'
        value: 'VALUE'
