---
data:
  i3:
    font_size: 13
    xrandr: ''
    tray_output: ''
    nm_applet: true
    additional_bindings: ''
  sway:
    font_size: 13
    tray_output: 'eDP-1'
    nm_applet: true
    additional_bindings: ''
    inputs: |-
      input <identifier> {
      }
    outputs: |-
      output <identifier> {
      }
  bumblebee:
    modules: 'ytrssil,'
    parameters:
      - key: "sensors.path"
        value: "coretemp-isa-0000/Package id 0/temp1_input"
  alacritty:
    font:
      size: '7.5'
      offset:
        x: 0
        y: 3
  rofi:
    font:
      size: '15'
  zshrc:
    env_vars:
      - name: 'NAME'
        value: 'VALUE'
  xinitrc:
    additional_commands: ''
