---
data:
  gui: true
  modern_cli: true
  hyprland:
    monitors:
      identifier: "resolution@refresh_rate, auto, 1, vrr, 0"
    input:
      keyboard_layouts: |-
        kb_layout = us,rs,rs,de
        kb_variant = ,latinunicode,,
      sensitivity: "1"
  waybar:
    top:
      extra_modules: ""
    bottom:
      cpu_temp_path: pci0000:00/0000:00:14.0/i2c-20/20-0050
      cpu_temp_filename: temp1_input
  ghostty:
    font:
      size: '14'
      cell_width: -1
      cell_height: 1
  rofi:
    font:
      size: '15'
  zshrc:
    env_vars:
      - name: 'NAME'
        value: 'VALUE'
