#!/bin/bash

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap" &
fi

xset fp rehash &
xset dpms 30000 30000 30000 &
xset s 30000 30000 &
xcape -e 'Control_L=Escape' &
xbindkeys &
sh $HOME/.fehbg &
dunst &

exec i3
