#!/bin/bash

/usr/bin/prime-offload &

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap" &
fi

source /etc/X11/xinit/xinitrc.d/50-systemd-user.sh

xset fp rehash &
xset dpms 30000 30000 30000 &
xset s 30000 30000 &
xcape -e 'Control_L=Escape' &
xbindkeys &
sh $HOME/.fehbg &
dunst &

exec i3
