[qwen3.5-4b]
hf = unsloth/Qwen3.5-4B-MTP-GGUF:UD-Q4_K_XL
n-gpu-layers = 99
ctx-size = 8192
flash-attn = on
parallel = 1
spec-type = draft-mtp
spec-draft-n-max = 6
reasoning = on

[ministral3-8b]
hf = unsloth/Ministral-3-8B-Instruct-2512-GGUF:UD-Q4_K_XL
n-gpu-layers = 99
ctx-size = 16384
flash-attn = on
jinja = true
temp = 0.15
parallel = 1

[qwen3.6-27b]
hf = unsloth/Qwen3.6-27B-MTP-GGUF:Q4_K_M
alias = qwen3.6-27b
n-gpu-layers = 99
flash-attn = on
jinja = true
ctx-size = 65536
temp = 0.9
top-p = 0.95
top-k = 20
min-p = 0.0
parallel = 1
spec-type = draft-mtp
spec-draft-n-max = 2
repeat-penalty = 1.0
reasoning = on

[supergemma4-26b]
hf = Jiunsong/supergemma4-26b-uncensored-gguf-v2:Q4_K_M
alias = supergemma4-26b
n-gpu-layers = 99
flash-attn = on
ctx-size = 65536
temp = 1.1
top-p = 0.95
top-k = 64
fit = off
reasoning = auto

[gemma4-26b]
hf = unsloth/gemma-4-26B-A4B-it-qat-GGUF:UD-Q4_K_XL
alias = gemma4-26B
n-gpu-layers = 99
n-gpu-layers-draft = 99
ngl=999
flash-attn = on
ctx-size = 65536
temp = 1.0
top-p = 0.95
top-k = 64
spec-type = draft-mtp
spec-draft-n-max = 4
fit = off
reasoning = auto

# [lfm2-24b]
# hf = LiquidAI/LFM2-24B-A2B-GGUF:Q4_K_M
# n-gpu-layers = 99
# ctx-size = 16384
# flash-attn = on
